### PR TITLE
remember to apt-get update during apt-get install RUN lines

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by simonvanderveldt** [comment]
Totally missed this, notifications were turned off for some reason. Thanks for the fix!

**Comment by simonvanderveldt** [comment]
@graingert I'd like to squash the changes/commits related to adding ZFS into a single commit, which means this commit would be squashed as well. I'll add a reference in the commit message of that single commit to this PR attributing this change to you, is that OK to you?

**Comment by graingert** [comment]
@simonvanderveldt squash away. I didn't get notifications for this either!

**Comment by graingert** [comment]
@simonvanderveldt send me a tweet if I don't respond.

**Comment by simonvanderveldt** [comment]
> @simonvanderveldt squash away. I didn't get notifications for this either!

@graingert OK, done :) Sorry for the noise!

**Pull request merged**
